export const categoryNames: { [key: string]: string } = {
  "phone-accessories": "Cep Telefonu-Aksesuar",
  "apple-phones": "Apple Telefonlar",
  "android-phones": "Android Telefonlar",
  "wearable-technologies": "Giyinebilir Teknolojiler",
  "computer-tablet": "Bilgisayar-Tablet",
  electrical: "Elektrikli Ev Aletleri",
  "white-goods": "Beyaz Eşya",
  "health-personal-care": "Sağlık-Kişisel Bakım",
  "hobby-game": "Hobi-Oyun",
  "tv-audio": "TV-Ses Sistemleri",
  "home-living": "Ev-Yaşam",
  "mom-baby-toys": "Anne-Bebek-Oyuncak",
  accessories: "Aksesuarlar",
};
