export const categoryNames: { [key: string]: string } = {
  "phone-accessories": "Cep Telefonu-Aksesuar",
  "computer-tablet": "Bilgisayar-Tablet",
  elektrik: "Elektrikli Ev Aletleri",
  beyaz: "Beyaz Eşya",
  saglik: "Sağlık-Kişisel Bakım",
  "hobby-game": "Hobi-Oyun",
  tv: "TV-Ses Sistemleri",
  ev: "Ev-Yaşam",
  anne: "Anne-Bebek-Oyuncak",
  "apple-phones": "Apple Telefonlar",
  "android-phones": "Android Telefonlar",
  "scooters-bicycles": "Scooterlar ve Bisikletler",
  "white-goods": "Beyaz Eşya",
  "heating-cooling-systems": "Isıtma ve Soğutma Sistemleri",
  "wearable-technologies": "Giyinebilir Teknolojiler",
  accessories: "Aksesuarlar",
  laptops: "Dizüstü Bilgisayarlar",
  "health-personal-care": "Sağlık ve Kişisel Bakım",
  "tv-audio": "TV ve Ses Sistemleri",
  "home-living": "Ev ve Yaşam",
  "mom-baby-toys": "Anne, Bebek ve Oyuncak",
};
